# Seu primeiro aplicativo Shiny

Neste capítulo, vamos descobrir o que é exatamente um aplicativo Shiny e o que ele precisa para funcionar. Vamos construir e rodar o nosso primeiro app, mostrando os componentes básicos existentes em qualquer aplicativo Shiny. Também daremos a nossa primeira olhadela no conceito de reatividade, um paradigma de programação diferente do que estamos acostumados na linguagem R e essencial para o Shiny funcionar adequadamente.

Antes de começarmos, você precisa ter o pacote `{shiny}` instalado.

```{r, eval = FALSE}
install.packages("shiny")
```

A versão do pacote que estamos utilizando neste livro é a `r packageVersion("shiny")`.

É uma boa prática criarmos novos repositórios (ou projetos, no RStudio) para cada nova análise de dados que começamos, mantendo todos os arquivos da análise dentro desse repositório. Veremos que, para aplicavios Shiny, isso será especialmente importante. Para reproduzir os exemplos deste livro, recomendamos criar uma nova pasta para cada aplicativo. Por mais que em alguns casos isso não seja particularmente útil, será uma boa maneira de praticar essa maneira de organização.

Para mais dicas de organização de projetos de análide de dados, em um contexto geral, recomendamos a leitura do [Zen do R](https://curso-r.github.io/zen-do-r/), especialmente o [Capítulo 3](https://curso-r.github.io/zen-do-r/rproj-dir.html).